sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t carpodiem/aws-beanstalk -f Dockerfile.dev .

script:
  - docker run -e CI=true carpodiem/aws-beanstalk npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "webapp-v1"
  env: "Webapp-v1-env"
  bucket_name: "elasticbeanstalk-eu-north-1-643587322618"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
