sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-643587322618"
  bucket_path: "docker"
  on:
    branch: main
